//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_CRUD.Entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int CLIE_PK_ID { get; set; }
        public string CLIE_NOME { get; set; }
        public Nullable<System.DateTime> CLIE_DATA_NASCIMENTO { get; set; }
        public string CLIE_TELEFONE { get; set; }
        public byte[] CLIE_IMAGEM { get; set; }
        public string CLIE_TIPO { get; set; }
        public string CLIE_EMAIL { get; set; }
        public string CLIE_CPF { get; set; }
        public string CLIE_CNPJ { get; set; }
        public Nullable<System.DateTime> CLIE_DATA_CADASTRO { get; set; }
        public int CLIE_STATUS { get; set; }
        public bool CLIE_EXCLUIDO { get; set; }
    }
}
